import {
  test as base,
  expect,
  type BrowserContext,
  type Frame,
  type Page,
} from "@playwright/test";
import { fileURLToPath } from "node:url";
import type { SyncPushChange, SyncRecord } from "@zsh-eng/local-sync";

export const SAMPLE_EPUB_PATH = fileURLToPath(
  new URL("../../fixtures/sample.epub", import.meta.url),
);
export const SAMPLE_BOOK_TITLE = /Alice.*Adventures.*Wonderland/i;
const DATABASE_MODULE = "/src/lib/sync-v2/db.ts";
const CURRENT_SPREAD = '[data-reader-spread-layer="current"]';

type PreparedLibrary = Record<string, Record<string, unknown>[]>;

/** A local, deterministic remote for UI tests. Protocol conflicts belong in integration tests. */
async function mockApi(context: BrowserContext, signedIn = false) {
  const records: SyncRecord[] = [];
  const pushed: SyncPushChange[] = [];
  const unexpected: string[] = [];
  await context.route("**/api/**", async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    const path = url.pathname;
    if (path === "/api/auth/get-session") {
      const now = new Date().toISOString();
      await route.fulfill({
        json: signedIn
          ? {
              user: {
                id: "test-user",
                name: "Test Reader",
                email: "reader@example.test",
                emailVerified: true,
                createdAt: now,
                updatedAt: now,
              },
              session: {
                id: "test-session",
                userId: "test-user",
                token: "local-test",
                expiresAt: new Date(Date.now() + 3600000).toISOString(),
                createdAt: now,
                updatedAt: now,
              },
            }
          : null,
      });
      return;
    }
    if (path === "/api/sync/v2/pull") {
      const cursor = Number(url.searchParams.get("cursor"));
      const head = url.searchParams.has("head")
        ? Number(url.searchParams.get("head"))
        : records.length;
      await route.fulfill({
        json: {
          records: records.filter(
            (record) =>
              record.serverSeq > cursor &&
              record.serverSeq <= head &&
              (url.searchParams.get("excludeOwnDevice") !== "true" ||
                record.deviceId !== request.headers()["x-device-id"]),
          ),
          cursor: head,
          head,
          hasMore: false,
        },
      });
      return;
    }
    if (path === "/api/sync/v2/push") {
      const { changes } = request.postDataJSON() as {
        changes: SyncPushChange[];
      };
      pushed.push(...changes);
      await route.fulfill({
        json: {
          results: changes.map((change) => {
            const winner = {
              ...change,
              deviceId: request.headers()["x-device-id"],
              serverSeq: records.length + 1,
            };
            records.push(winner);
            return { accepted: true, winner };
          }),
        },
      });
      return;
    }
    unexpected.push(`${request.method()} ${path}`);
    await route.fulfill({
      status: 501,
      json: { error: "Unexpected test API request" },
    });
  });
  return {
    pushed,
    unexpected,
    enqueue(change: SyncPushChange) {
      records.push({
        ...change,
        deviceId: "remote-test-device",
        serverSeq: records.length + 1,
      });
    },
  };
}

/** Each test gets a fresh context. Only immutable imported data is shared between workers' tests. */
export const test = base.extend<
  {
    signedIn: boolean;
    remote: Awaited<ReturnType<typeof mockApi>>;
    addSampleBook: () => Promise<void>;
    localBook: { id: string };
  },
  { preparedLibrary: PreparedLibrary }
>({
  signedIn: [false, { option: true }],
  remote: [
    async ({ context, signedIn }, use) => {
      const remote = await mockApi(context, signedIn);
      await use(remote);
      expect(remote.unexpected, "Unexpected API requests").toEqual([]);
    },
    { auto: true },
  ],
  addSampleBook: async ({ page }, use) => use(() => importSampleBook(page)),
  preparedLibrary: [
    async ({ browser }, use, workerInfo) => {
      const context = await browser.newContext({ serviceWorkers: "block" });
      let snapshot: PreparedLibrary;
      try {
        const remote = await mockApi(context);
        const page = await context.newPage();
        await page.goto(workerInfo.project.use.baseURL!);
        // The first worker also loads Vite's cold application module graph.
        // Wait for the actual Library control before starting the import flow.
        await expect(
          page.getByRole("button", { name: "Import EPUB", exact: true }),
        ).toBeVisible({ timeout: 15_000 });
        await importSampleBook(page);
        // Blobs need an explicit encoding when crossing the Playwright boundary.
        // Keep the stored rows, including their schema, generated by the real importer.
        snapshot = await page.evaluate(async (modulePath) => {
          const { syncV2Db: db } = await import(modulePath);
          const tables = [
            "books",
            "files",
            "bookFiles",
            "bookMaterializations",
          ];
          return Object.fromEntries(
            await Promise.all(
              tables.map(async (table) => {
                const rows = await db.table(table).toArray();
                for (const row of rows) {
                  for (const [key, value] of Object.entries(row)) {
                    if (!(value instanceof Blob)) continue;
                    const dataUrl = await new Promise<string>(
                      (resolve, reject) => {
                        const reader = new FileReader();
                        reader.onload = () => resolve(reader.result as string);
                        reader.onerror = () => reject(reader.error);
                        reader.readAsDataURL(value);
                      },
                    );
                    row[key] = { blobDataUrl: dataUrl };
                  }
                }
                return [table, rows];
              }),
            ),
          );
        }, DATABASE_MODULE);
        expect(remote.unexpected).toEqual([]);
      } finally {
        await context.close();
      }
      await use(snapshot);
    },
    { scope: "worker" },
  ],
  localBook: async ({ page, preparedLibrary }, use) => {
    await page.goto("/");
    await page.evaluate(
      async ({ snapshot, modulePath }) => {
        const { syncV2Db: db } = await import(modulePath);
        const tables = Object.entries(snapshot);
        for (const [, rows] of tables) {
          for (const row of rows) {
            for (const [key, value] of Object.entries(row)) {
              if (
                value &&
                typeof value === "object" &&
                "blobDataUrl" in value
              ) {
                row[key] = await (
                  await fetch(value.blobDataUrl as string)
                ).blob();
              }
            }
          }
        }
        await db.transaction(
          "rw",
          tables.map(([table]) => db.table(table)),
          async () => {
            for (const [table, rows] of tables)
              await db.table(table).bulkPut(rows);
          },
        );
      },
      { snapshot: preparedLibrary, modulePath: DATABASE_MODULE },
    );
    await expect(
      page.getByRole("heading", { name: SAMPLE_BOOK_TITLE }),
    ).toBeVisible();
    await use({ id: preparedLibrary.books[0].id as string });
  },
});

export { expect };

export async function importSampleBook(page: Page): Promise<void> {
  const importButton = page.getByRole("button", {
    name: "Import EPUB",
    exact: true,
  });
  await expect(importButton).toBeVisible();
  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    importButton.click(),
  ]);
  await fileChooser.setFiles(SAMPLE_EPUB_PATH);
  await expect(
    page.getByRole("heading", { name: SAMPLE_BOOK_TITLE }),
  ).toBeVisible({ timeout: 30_000 });
}

/** Wait for the current spread only, including removal of the outgoing animated spread. */
export async function waitForReaderReady(page: Page | Frame): Promise<void> {
  await expect(
    page.locator(`${CURRENT_SPREAD} [data-reader-page-content]`).first(),
  ).toBeVisible();
  await page.waitForFunction((selector) => {
    const spread = document.querySelector(selector);
    if (!spread || spread.children.length !== 1) return false;
    if (spread.querySelector("[data-reader-image-pending]")) return false;
    const moving = spread
      .getAnimations({ subtree: true })
      .some((animation) => animation.playState === "running");
    const images = [...spread.querySelectorAll("img")];
    return (
      !moving &&
      document.fonts.status === "loaded" &&
      images.every((image) => image.complete && image.naturalWidth > 0)
    );
  }, CURRENT_SPREAD);
}

export async function currentPages(page: Page): Promise<string[]> {
  return page
    .locator(`${CURRENT_SPREAD} [data-reader-current-page]`)
    .evaluateAll((elements) =>
      elements.map(
        (element) => element.getAttribute("data-reader-current-page")!,
      ),
    );
}

export async function nextSpread(page: Page): Promise<void> {
  const before = await currentPages(page);
  await page.keyboard.press("ArrowRight");
  await expect.poll(() => currentPages(page)).not.toEqual(before);
  await waitForReaderReady(page);
}

export async function openLocalBook(page: Page, bookId: string): Promise<void> {
  // Direct entry tests startup from prepared storage without depending on hover prefetch.
  await page.goto(`/reader/${bookId}`);
  await waitForReaderReady(page);
}

/** Shows the phone reading chrome, which carries the Notes Island capsule. */
export async function showNotesCapsule(page: Page): Promise<void> {
  const capsule = page.locator("[data-notes-capsule]");
  // A notice from the previous action owns the bottom edge for a moment.
  await expect(page.locator("[data-notes-island]")).toHaveCount(0);
  if (!(await capsule.isVisible())) {
    const spread = (await page
      .locator('[data-reader-spread-layer="current"]')
      .boundingBox())!;
    await page.touchscreen.tap(
      spread.x + spread.width / 2,
      spread.y + spread.height / 2,
    );
  }
  await expect(capsule).toBeVisible();
}
