import * as stylex from "@stylexjs/stylex";

// Runtime variables live on the document root. Portals and Pierre's shadow
// hosts inherit them while StyleX keeps all component rules statically compiled.
export const tokens = stylex.defineVars({
  canvas: "var(--med-canvas, #171717)",
  panel: "var(--med-panel, #1c1c1c)",
  raised: "var(--med-raised, #242424)",
  hover: "var(--med-hover, #2d2d2d)",
  border: "var(--med-border, #343434)",
  text: "var(--med-text, #ededed)",
  muted: "var(--med-muted, #a1a1a1)",
  faint: "var(--med-faint, #737373)",
  accent: "var(--med-accent, #a5c9ff)",
  selected: "var(--med-selected, #29384d)",
  green: "var(--med-green, #8bcba0)",
  red: "var(--med-red, #e49ba3)",
  warning: "var(--med-warning, #e8c17a)",
  shadow: "var(--med-shadow, 0 14px 48px #00000060)",
  code: '"Geist Mono", "SFMono-Regular", Consolas, monospace',
  ui: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
});

export const ui = stylex.create({
  instant: {
    animationName: "none",
    transitionProperty: "none",
    scrollBehavior: "auto",
  },
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 28,
    paddingBlock: 3,
    paddingInline: 8,
    borderWidth: 0,
    borderRadius: 7,
    backgroundColor: { default: "transparent", ":hover": tokens.hover },
    color: tokens.muted,
    fontFamily: tokens.ui,
    fontSize: 12,
    lineHeight: 1.5,
    cursor: "pointer",
    whiteSpace: "nowrap",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.accent}` },
    outlineOffset: -2,
    opacity: { default: 1, ":disabled": 0.4 },
  },
  pressable: {
    transform: { default: "scale(1)", ":active:not(:disabled)": "scale(0.96)" },
    transitionProperty: "transform",
    transitionDuration: { default: "90ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: "ease-out",
  },
  active: { color: tokens.accent, backgroundColor: tokens.selected },
  strong: { color: tokens.text },
  primary: {
    color: tokens.canvas,
    backgroundColor: { default: tokens.accent, ":hover": tokens.accent },
    fontWeight: 600,
  },
  iconButton: { width: 28, minWidth: 28, paddingInline: 0 },
  input: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: tokens.border, ":focus": tokens.accent },
    borderRadius: 7,
    paddingBlock: 6,
    paddingInline: 9,
    backgroundColor: tokens.canvas,
    color: tokens.text,
    fontFamily: tokens.ui,
    fontSize: 12,
    outline: "none",
  },
  popup: {
    boxSizing: "border-box",
    minWidth: 200,
    maxHeight: "min(420px, 70vh)",
    overflowY: "auto",
    backgroundColor: tokens.raised,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.border,
    borderRadius: 12,
    padding: 5,
    boxShadow: tokens.shadow,
    color: tokens.text,
    fontFamily: tokens.ui,
    fontSize: 12,
    outline: "none",
    zIndex: 50,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 24,
    minHeight: 30,
    paddingInline: 9,
    borderRadius: 7,
    cursor: "default",
    outline: "none",
    backgroundColor: { default: "transparent", ":hover": tokens.hover },
    color: tokens.text,
    fontSize: 12,
  },
  menuHighlighted: { backgroundColor: tokens.hover },
  separator: { height: 1, backgroundColor: tokens.border, borderWidth: 0, marginBlock: 5 },
  muted: { color: tokens.muted },
  faint: { color: tokens.faint },
  mono: { fontFamily: tokens.code, fontSize: 11 },
  badge: {
    fontSize: 10,
    lineHeight: "18px",
    paddingInline: 5,
    borderRadius: 4,
    backgroundColor: tokens.hover,
    color: tokens.muted,
  },
  grow: { flex: "1" },
  row: { display: "flex", alignItems: "center", gap: 7, minWidth: 0 },
  truncate: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", minWidth: 0 },
  added: { color: tokens.green },
  removed: { color: tokens.red },
});
