import * as stylex from "@stylexjs/stylex";

// Runtime variables live on the document root. Portals and Pierre's shadow
// hosts inherit them while StyleX keeps all component rules statically compiled.
export const tokens = stylex.defineVars({
  canvas: "var(--med-canvas, #141416)",
  panel: "var(--med-panel, #0d0d0f)",
  raised: "var(--med-raised, #1b1b1e)",
  hover: "var(--med-hover, #232327)",
  border: "var(--med-border, #28282d)",
  text: "var(--med-text, #ececef)",
  muted: "var(--med-muted, #9d9da6)",
  faint: "var(--med-faint, #686871)",
  accent: "var(--med-accent, #8f9cff)",
  selected: "var(--med-selected, #252946)",
  green: "var(--med-green, #82cfa1)",
  red: "var(--med-red, #ee8d98)",
  warning: "var(--med-warning, #e8c17a)",
  shadow: "var(--med-shadow, 0 12px 32px -8px #000000b3)",
  // Translucent layers derive from each theme's text color. One hairline or
  // hover then reads the same on the frame, the review card, and popovers.
  line: "color-mix(in srgb, var(--med-text, #ececef) 8%, transparent)",
  lineStrong: "color-mix(in srgb, var(--med-text, #ececef) 14%, transparent)",
  fill: "color-mix(in srgb, var(--med-text, #ececef) 5%, transparent)",
  fillStrong: "color-mix(in srgb, var(--med-text, #ececef) 9%, transparent)",
  accentSoft: "color-mix(in srgb, var(--med-accent, #8f9cff) 15%, transparent)",
  accentLine: "color-mix(in srgb, var(--med-accent, #8f9cff) 55%, transparent)",
  // Dialog scrim from the frame color: it dims dark themes and frosts light ones.
  scrim: "color-mix(in srgb, var(--med-panel, #0d0d0f) 62%, transparent)",
  // Strong ease-out for entering UI; ease-in-out for elements that move on screen.
  easeOut: "cubic-bezier(0.23, 1, 0.32, 1)",
  easeInOut: "cubic-bezier(0.77, 0, 0.175, 1)",
  code: '"Paper Mono", "SFMono-Regular", Consolas, monospace',
  ui: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
});

const reduced = "@media (prefers-reduced-motion: reduce)";

export const ui = stylex.create({
  // Keyboard-opened palettes and high-frequency surfaces appear immediately.
  instant: {
    animationName: "none",
    transitionProperty: "none",
    scrollBehavior: "auto",
  },
  // Pointer-opened menus grow from their trigger. Base UI sets the origin and
  // keeps the popup mounted until the exit transition ends.
  pop: {
    transformOrigin: "var(--transform-origin)",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: tokens.easeOut,
    transitionDuration: {
      default: "150ms",
      ":is([data-ending-style])": "90ms",
      ":is([data-instant])": "0ms",
      [reduced]: "0ms",
    },
    opacity: { default: 1, ":is([data-starting-style], [data-ending-style])": 0 },
    transform: {
      default: "scale(1)",
      ":is([data-starting-style], [data-ending-style])": "scale(0.96)",
    },
  },
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    boxSizing: "border-box",
    minHeight: 28,
    paddingBlock: 0,
    paddingInline: 8,
    borderWidth: 0,
    borderRadius: 6,
    backgroundColor: { default: "transparent", ":hover:not(:disabled)": tokens.fill },
    color: { default: tokens.muted, ":hover:not(:disabled)": tokens.text },
    fontFamily: tokens.ui,
    fontSize: 12,
    fontWeight: 450,
    lineHeight: 1.5,
    cursor: "pointer",
    whiteSpace: "nowrap",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.accentLine}` },
    outlineOffset: -1,
    opacity: { default: 1, ":disabled": 0.4 },
  },
  pressable: {
    transform: { default: "scale(1)", ":active:not(:disabled)": "scale(0.97)" },
    transitionProperty: "transform",
    transitionDuration: { default: "100ms", [reduced]: "0ms" },
    transitionTimingFunction: tokens.easeOut,
  },
  active: {
    color: { default: tokens.accent, ":hover:not(:disabled)": tokens.accent },
    backgroundColor: { default: tokens.accentSoft, ":hover:not(:disabled)": tokens.accentSoft },
  },
  strong: { color: tokens.text, fontWeight: 500 },
  primary: {
    color: { default: tokens.canvas, ":hover:not(:disabled)": tokens.canvas },
    backgroundColor: {
      default: tokens.text,
      ":hover:not(:disabled)": `color-mix(in srgb, ${tokens.text} 86%, ${tokens.canvas})`,
    },
    fontWeight: 500,
  },
  // A quiet outlined button for secondary actions that need an edge, such as Push.
  outlined: {
    boxShadow: `inset 0 0 0 1px ${tokens.line}`,
    color: { default: tokens.text, ":hover:not(:disabled)": tokens.text },
  },
  iconButton: { width: 28, minWidth: 28, paddingInline: 0 },
  input: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    height: 28,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: tokens.line, ":hover": tokens.lineStrong, ":focus": tokens.accentLine },
    borderRadius: 6,
    paddingBlock: 0,
    paddingInline: 9,
    backgroundColor: tokens.fill,
    color: tokens.text,
    fontFamily: tokens.ui,
    fontSize: 12,
    outline: "none",
    boxShadow: { default: "none", ":focus": `0 0 0 3px ${tokens.accentSoft}` },
  },
  popup: {
    boxSizing: "border-box",
    minWidth: 200,
    maxHeight: "min(420px, 70vh)",
    overflowY: "auto",
    backgroundColor: tokens.raised,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.lineStrong,
    borderRadius: 10,
    padding: 4,
    boxShadow: tokens.shadow,
    color: tokens.text,
    fontFamily: tokens.ui,
    fontSize: 12,
    outline: "none",
    zIndex: 50,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 24,
    minHeight: 28,
    paddingInline: 8,
    borderRadius: 6,
    cursor: "default",
    outline: "none",
    backgroundColor: { default: "transparent", ":hover": tokens.fillStrong },
    color: tokens.text,
    fontSize: 12,
  },
  menuHighlighted: { backgroundColor: tokens.fillStrong },
  // Shared surface for keyboard palettes: commands, files, symbols, branches, themes.
  palette: {
    position: "fixed",
    top: "16vh",
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(600px, calc(100vw - 32px))",
    boxSizing: "border-box",
    backgroundColor: tokens.raised,
    color: tokens.text,
    fontFamily: tokens.ui,
    fontSize: 12.5,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.lineStrong,
    boxShadow: tokens.shadow,
    overflow: "hidden",
    outline: "none",
  },
  scrim: { position: "fixed", inset: 0, backgroundColor: tokens.scrim },
  paletteInput: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minHeight: 48,
    paddingInline: 14,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.line,
    color: tokens.faint,
  },
  paletteField: {
    flex: "1",
    minWidth: 0,
    borderWidth: 0,
    outline: "none",
    backgroundColor: "transparent",
    color: tokens.text,
    fontFamily: tokens.ui,
    fontSize: 14,
    "::placeholder": { color: tokens.faint },
  },
  paletteFooter: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    minHeight: 34,
    paddingInline: 14,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.line,
    color: tokens.faint,
    fontSize: 11,
  },
  separator: { height: 1, backgroundColor: tokens.line, borderWidth: 0, marginBlock: 4 },
  muted: { color: tokens.muted },
  faint: { color: tokens.faint },
  mono: { fontFamily: tokens.code, fontSize: 11, fontVariantNumeric: "tabular-nums" },
  badge: {
    fontSize: 10,
    lineHeight: "18px",
    paddingInline: 5,
    borderRadius: 4,
    backgroundColor: tokens.fill,
    color: tokens.muted,
  },
  grow: { flex: "1" },
  row: { display: "flex", alignItems: "center", gap: 7, minWidth: 0 },
  truncate: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", minWidth: 0 },
  added: { color: tokens.green, fontVariantNumeric: "tabular-nums" },
  removed: { color: tokens.red, fontVariantNumeric: "tabular-nums" },
});
